### ISSUE TITLE
Is it possible to export as .ply format?

### ISSUE THREAD

**Issue by mitchell-saunders** [openai/point-e#60]
This is all amazing thank you! 

I was wondering if it's possible to export and save the point cloud data in the .ply format?

**Comment by kevincolten** [comment]
Yes! You can look at their example pointcloud2mesh.ipynb or here is a version I am playing with in Google Colab that goes from start (from text or images) to finish (export to ply, obj, or glb)
https://gist.github.com/kevincolten/56529dcb4a42ea3e159e76322a9980e6

**Comment by mitchell-saunders** [comment]
Thanks, I'll give that a shot!

**Comment by mitchell-saunders** [comment]
I'm getting this error, do you know why this might be?
![error](https://user-images.githubusercontent.com/86245128/212646694-ebe55733-e50d-4410-a605-213f77f85b26.jpg)

**Comment by kevincolten** [comment]
Yeah, it's because I mucked up that notebook It's auto saved by colab, so it saves my errors, too.

Try updating this line
<img width="782" alt="Screenshot 2023-01-16 at 1 23 06 PM" src="https://user-images.githubusercontent.com/4411115/212752648-6577bf5f-0840-4e80-a452-0cb9be747cdd.png">

`num_points=[1024, 4096 - 1024],`

**Comment by mitchell-saunders** [comment]
Amazing thank you got it working!
